ALTER TABLE document ADD COLUMN parse_job_id VARCHAR(80) NULL;
ALTER TABLE document ADD COLUMN lease_until DATETIME NULL;
ALTER TABLE document ADD COLUMN heartbeat_at DATETIME NULL;
ALTER TABLE document ADD COLUMN embedding_model VARCHAR(120) NULL;
ALTER TABLE document ADD COLUMN deleted_at DATETIME NULL;
ALTER TABLE outbox_message ADD COLUMN dead_letter_reason VARCHAR(500) NULL;
ALTER TABLE outbox_message ADD COLUMN dispatched_at DATETIME NULL;
CREATE INDEX idx_document_parse_lease ON document(status,lease_until,heartbeat_at);
CREATE INDEX idx_outbox_dead_letter ON outbox_message(status,updated_at);
ALTER TABLE knowledge_base ADD CONSTRAINT fk_kb_owner FOREIGN KEY (owner_id) REFERENCES app_user(id);
ALTER TABLE kb_acl ADD CONSTRAINT fk_acl_kb FOREIGN KEY (kb_id) REFERENCES knowledge_base(id);
ALTER TABLE kb_acl ADD CONSTRAINT fk_acl_subject FOREIGN KEY (subject_id) REFERENCES app_user(id);
ALTER TABLE document ADD CONSTRAINT fk_document_kb FOREIGN KEY (kb_id) REFERENCES knowledge_base(id);
ALTER TABLE document ADD CONSTRAINT fk_document_owner FOREIGN KEY (owner_id) REFERENCES app_user(id);
ALTER TABLE document_chunk ADD CONSTRAINT fk_chunk_document FOREIGN KEY (document_id) REFERENCES document(id) ON DELETE CASCADE;
ALTER TABLE document_chunk_term ADD CONSTRAINT fk_term_chunk FOREIGN KEY (chunk_id) REFERENCES document_chunk(id) ON DELETE CASCADE;
ALTER TABLE chat_conversation ADD CONSTRAINT fk_conversation_kb FOREIGN KEY (kb_id) REFERENCES knowledge_base(id);
ALTER TABLE chat_conversation ADD CONSTRAINT fk_conversation_user FOREIGN KEY (user_id) REFERENCES app_user(id);
ALTER TABLE chat_message ADD CONSTRAINT fk_message_conversation FOREIGN KEY (conversation_id) REFERENCES chat_conversation(id) ON DELETE CASCADE;
ALTER TABLE agent_approval ADD CONSTRAINT fk_approval_user FOREIGN KEY (user_id) REFERENCES app_user(id);
ALTER TABLE agent_approval ADD CONSTRAINT fk_approval_conversation FOREIGN KEY (conversation_id) REFERENCES chat_conversation(id) ON DELETE CASCADE;
